Capitals = {"United States of America": "Washington",
             "France": "Paris",
             "Allemagne": "Berlin",
             "Italie": "Rome",
             "Espagne": "Madrid",
             "Portugal": "Lisbonne",
             "Angleterre": "Londres",
             "Pays-Bas": "Amsterdam",
             "Belgique": "Bruxelles",
             "Suisse": "Berne",
             "Autriche": "Vienne",
             "Pologne": "Varsovie",
             "Danemark": "Copenhague",
             "Norvège": "Oslo",
             "Suède": "Stockholm",
             "Finlande": "Helsinki",
             "Russie": "Moscou",
             "Grèce": "Athènes",
             "Turquie": "Ankara",
             "Canada": "Ottawa",
             "Australia": "Canberra",
             "India": "New Delhi",
             "China": "Beijing",
             "Japan": "Tokyo",
             "South Korea": "Seoul",
             "Mexico": "Mexico City",
             "Brazil": "Brasilia",
             "Argentina": "Buenos Aires",
             "South Africa": "Pretoria",
             "Egypt": "Cairo",
             "New Zealand": "Wellington",
             "Saudi Arabia": "Riyadh",
             "United Arab Emirates": "Abu Dhabi",
             "Indonesia": "Jakarta",
             "Thailand": "Bangkok",
             "Malaysia": "Kuala Lumpur",
             "Singapore": "Singapore",
             "Vietnam": "Hanoi",
             "Philippines": "Manila",
             "Ireland": "Dublin",
             "Iceland": "Reykjavik",
             "Luxembourg": "Luxembourg",
             "Monaco": "Monaco",
             "San Marino": "San Marino",
             "Liechtenstein": "Vaduz",
             "Malta": "Valletta",
             "Andorra": "Andorra la Vella",
             "Slovakia": "Bratislava",
             "Slovenia": "Ljubljana",
             "Croatia": "Zagreb",
             "Bosnia and Herzegovina": "Sarajevo",
             "Montenegro": "Podgorica",
             "Serbia": "Belgrade",
             "Kosovo": "Pristina",
             "North Macedonia": "Skopje",
             "Albania": "Tirana",
             "Bulgaria": "Sofia",
             "Romania": "Bucharest",
             "Hungary": "Budapest",
             "Czech Republic": "Prague",
             "Lithuania": "Vilnius",
             "Latvia": "Riga",
             "Estonia": "Tallinn",
             "Ukraine": "Kyiv",
             "Belarus": "Minsk",
             "Moldova": "Chisinau",
             "Algeria": "Algiers",
             "Bahrain": "Manama",
             "Comoros": "Moroni",
             "Djibouti": "Djibouti",
             "Iraq": "Baghdad",
             "Jordan": "Amman",
             "Kuwait": "Kuwait City",
             "Lebanon": "Beirut",
             "Libya": "Tripoli",
             "Mauritania": "Nouakchott",
             "Morocco": "Rabat",
             "Oman": "Muscat",
             "Palestine": "Jerusalem",
             "Qatar": "Doha",
             "Somalia": "Mogadishu",
             "Sudan": "Khartoum",
             "Syria": "Damascus",
             "Tunisia": "Tunis",
             "Yemen": "Sana'a"}

while True:
    country = input("Enter a country (C to see available )(Q to quit): ").capitalize()
    print()
    if country.lower() == "q":
        break
    elif country.lower() == "c":
        for x in Capitals:
            print(x)
           
    elif country in Capitals:
        print("----------------------------------------------------------------------------------")
        print(f"The capital of {country} is {Capitals.get(country)}")
        print("----------------------------------------------------------------------------------")
    else:
        print(f"Please contact the creator to add {country} capital")
    print()